name: Deploy Jekyll Site

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整提交历史

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'  # 需与Gemfile一致
          bundler-cache: true
          cache-version: 3  # 更新缓存版本号

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          # 解决Windows路径问题
          sudo apt-get install dos2unix
          find . -type f -name "*.sh" -exec dos2unix {} \;
          
          # 安装依赖
          npm install bootstrap @popperjs/core
          bundle config path vendor/bundle
          bundle install --retry 3 --jobs 4
          bundle add webrick

      - name: Prepare assets
        run: |
          mkdir -p _sass/vendors
          cp -r node_modules/bootstrap/scss _sass/vendors/bootstrap
          cp node_modules/@popperjs/core/dist/umd/popper.min.js assets/js/

      - name: Build site
        run: |
          bundle exec jekyll clean
          bundle exec jekyll build --trace --baseurl ""
          # 统一路径格式
          find _site -type f -exec sed -i 's/\\/\//g' {} \;
        env:
          JEKYLL_ENV: production

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: jekyll-site
          path: _site/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4