name: Deploy Jekyll site

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Clean Install
        run: |
          rm -rf vendor/bundle
          bundle install --redownload

      - name: Build
        run: |
          bundle exec jekyll build --baseurl ""
          find _site -type f -name "*" -exec sed -i 's/\\/\//g' {} \;

      - name: Deploy
        uses: actions/upload-pages-artifact@v3

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
